name: Continuous Integration
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    strategy:
      matrix:
        bun_version: [1.0.30]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Bun ${{ matrix.bun_version }}
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ matrix.bun_version }}
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Run CI check
        run: bun run ci
