name: Publish

on:
  workflow_dispatch:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  npm:
    name: Publish lib to npmjs.com
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        bun_version: [1.0.30]
        os: [ubuntu-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Bun ${{ matrix.bun_version }}
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ matrix.bun_version }}

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build project
        run: bun run build

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org"

      - name: Publish lib to npmjs.com
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: |
          npm publish
